import json,sys,re
sys.path.insert(0,'/home/claude/i18n')
from ahklit import encode
P='/home/claude/mm-src/src/99_translations.ahk'   # generated part of the app; run tools/build.py afterwards
s=open(P,encoding='utf-8').read()
BEGIN='; ===== TRANSLATIONS (generated by i18n/gen_tables.py - edit the JSON files, not this block) ====='
END='; ===== END TRANSLATIONS ====='
s=''
keys=json.load(open('/home/claude/i18n/keys.json',encoding='utf-8'))
out=[BEGIN]
for code,fn in (('cs','TrCs'),('pl','TrPl'),('de','TrDe')):
    t=json.load(open(f'/home/claude/i18n/{code}.json',encoding='utf-8'))
    out.append(f'{fn}() {{\n    m := Map()')
    for k in keys:
        tr=t[k]
        out.append(f'    m["{encode(k)}"] := "{encode(tr)}"')
    out.append('    return m\n}')
out.append(END)
s='\n'.join(out)+'\n'
open(P,'w',encoding='utf-8').write(s)
print('tables written',len(keys))
